// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hailstone.core.Data;

namespace hailstone.core.Migrations
{
    [DbContext(typeof(HailstoneDbContext))]
    [Migration("20191024213549_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("hailstone.core.Models.HailstoneData", b =>
                {
                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("HailstoneNumber");

                    b.HasKey("Number");

                    b.ToTable("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
